name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels:
  - bug
  - triage
  - priority:high
  - priority:medium
  - priority:low
  - status:awaiting-feedback
  - status:in-progress
  - status:on-hold
body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to fill out a bug report!"
  - type: input
    id: bug-summary
    attributes:
      label: Bug Summary
      description: Briefly describe the bug.
      placeholder: "A concise summary of the bug"
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: "Please list the steps to reproduce the issue:"
      placeholder: "1. ..., 2. ..., 3. ..."
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
      placeholder: "The expected outcome"
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened.
      placeholder: "The actual outcome"
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: Version of the software or project being used.
      placeholder: "Version or commit hash"
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: "Logs, etc."
  - type: dropdown
    id: severity
    attributes:
      label: Bug Severity
      description: "Select the severity of the bug."
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Bug Priority
      description: "Select the priority of the bug."
      options:
        - Immediate
        - Soon
        - Eventually
    validations:
      required: true
  - type: input
    id: system-information
    attributes:
      label: System Information
      description: "Include details like OS, browser version, and hardware configuration."
      placeholder: "OS, Browser, Hardware"
    validations:
      required: false
  - type: checkboxes
    id: regression
    attributes:
      label: Regression
      description: "Check if the issue is a regression."
      options:
        - label: "Yes, the issue is a regression."
  - type: textarea
    id: workarounds
    attributes:
      label: Workarounds
      description: "Describe any potential workarounds you've identified."
      placeholder: "Any temporary solutions or workarounds"
