name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels:
  - enhancement
  - triage
body:
  - type: markdown
    attributes:
      value: "Thanks for suggesting a feature!"
  - type: input
    id: feature-summary
    attributes:
      label: Feature Summary
      description: Briefly describe the feature.
      placeholder: "A concise summary of the feature"
    validations:
      required: true
  - type: textarea
    id: feature-description
    attributes:
      label: Detailed Description
      description: "Describe the feature in detail:"
      placeholder: "A detailed description of the feature"
    validations:
      required: true
  - type: textarea
    id: motivation-benefits
    attributes:
      label: Motivation and Benefits
      description: Explain why this feature is important.
      placeholder: "Why this feature is beneficial"
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
      placeholder: "Screenshots, mockups, etc."
