openapi: 3.0.0
info:
  title: Repro3D API
  version: 1.0.0
  description: API for managing receipts and redeem codes.

servers:
  - url: 'http://localhost:8074'
    description: Development server

paths:
  /api/receipt:
    get:
      summary: Retrieves all receipts.
      operationId: getAllReceipts
      responses:
        '200':
          description: List of all receipts.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Receipt'
    post:
      summary: Creates a new receipt.
      operationId: createReceipt
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Receipt'
      responses:
        '200':
          description: Receipt created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'

  /api/receipt/{id}:
    get:
      summary: Retrieves a receipt by ID.
      operationId: getReceiptById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Receipt retrieved successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
    put:
      summary: Updates a receipt by ID.
      operationId: updateReceipt
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Receipt'
      responses:
        '200':
          description: Receipt updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
    delete:
      summary: Deletes a receipt by ID.
      operationId: deleteReceipt
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Receipt deleted successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'

  /api/redeem-code:
    get:
      summary: Retrieves all redeem codes.
      operationId: getAllRedeemCodes
      responses:
        '200':
          description: List of all redeem codes.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RedeemCode'
    post:
      summary: Creates a new redeem code.
      operationId: createRedeemCode
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RedeemCode'
      responses:
        '200':
          description: Redeem code created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'

  /api/redeem-code/{id}:
    get:
      summary: Retrieves a redeem code by ID.
      operationId: getRedeemCodeById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Redeem code retrieved successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
    put:
      summary: Updates a redeem code by ID.
      operationId: updateRedeemCode
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RedeemCode'
      responses:
        '200':
          description: Redeem code updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
    delete:
      summary: Deletes a redeem code by ID.
      operationId: deleteRedeemCode
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Redeem code deleted successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'

components:
  schemas:
    Receipt:
      type: object
      properties:
        receiptId:
          type: integer
        paidOn:
          type: string
        sumTotal:
          type: integer
        order:
          $ref: '#/components/schemas/Order'

    RedeemCode:
      type: object
      properties:
        rc_id:
          type: integer
        rcCode:
          type: string
        used:
          type: boolean

    Order:
      type: object
      properties:
        order_id:
          type: integer
        orderDate:
          type: string
          format: date-time
        user:
          $ref: '#/components/schemas/User'
        redeemCode:
          $ref: '#/components/schemas/RedeemCode'

    User:
      type: object
      properties:
        userId:
          type: integer
        email:
          type: string
        billingAddress:
          type: string
        role:
          $ref: '#/components/schemas/Role'

    Role:
      type: object
      properties:
        roleId:
          type: integer
        roleName:
          type: string

    ApiResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        data:
          type: object
          nullable: true
          description: "This can be any type of JSON object or an array of objects, depending on the endpoint's operation context."
