name: CI Jira Xray

on:
  push:
    branches: [ "develop", "release" ]
  pull_request:
    branches: [ "develop", "release" ]

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
    - name: Checkout 
      uses: actions/checkout@v4.1.1
    - name: Set up Java
      uses: actions/setup-java@v1.0.0
      with:
        version: '21'  
    - name: Cache Maven packages
      uses: actions/cache@v4.0.2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: mvn clean compile test --file pom.xml
    - name: Submit results to Xray
      uses: mikepenz/xray-action@v3.0.4
      with:
        username: ${{ secrets.xray_client_id }}
        password: ${{ secrets.xray_client_secret }}
        testFormat: "junit"
        testPaths: "**/surefire-reports/*.xml"
        projectKey: "RP"